	# k8s/deployment.yaml
	apiVersion: apps/v1
	kind: Deployment
	metadata:
	  name: my-argo-app
	spec:
	  replicas: 2
	  selector:
	    matchLabels:
	      app: my-argo-app
	  template:
	    metadata:
	      labels:
	        app: my-argo-app
	    spec:
	      containers:
	      - name: my-argo-app
	        image: <your-docker-image>
	        ports:
	        - containerPort: 3000


