	# k8s/service.yaml
	apiVersion: v1
	kind: Service
	metadata:
	  name: my-argo-app
	spec:
	  selector:
	    app: my-argo-app
	  ports:
	    - protocol: TCP
	      port: 80
	      targetPort: 3000
	  type: LoadBalancer


